# Setup
title:        Keep coding, Keep thinking
tagline:      ""
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       dingyaguang117
  url:        "http://www.co-ding.com"

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman

plugins:
  - jekyll-feed